### ISSUE TITLE
Kickoff Meeting Wed May 27 2015 

### ISSUE THREAD

**Issue by mhdawson** [nodejs/benchmarking#1]
Sorry for the late notice but meeting was being arranged before repo was available.

The kickoff meeting is scheduled for Wed May 27 2015 at 2:00 PM EST.  

If you would like to attend you can add to you calender with this link:
<a target="_blank" href="https://www.google.com/calendar/event?action=TEMPLATE&tmeid=ZnU3ajAzNGt1OGhmaXJpMDluaTA3cXRhdGcgbWhkYXdzb25pYm1AbQ&tmsrc=mhdawsonibm%40gmail.com"><img border="0" src="https://www.google.com/calendar/images/ext/gc_button1_en.gif"></a>

and I believe this is the google hangouts link 

https://plus.google.com/hangouts/_/calendar/bWhkYXdzb25pYm1AZ21haWwuY29t.fu7j034ku8hfiri09ni07qtatg?authuser=0

The initial agenda will be:

1) Governance - review boilerplates and agree/disagree to use for this project
   https://github.com/nodejs/benchmarking/blob/master/CONTRIBUTING-draft.md
   https://github.com/nodejs/benchmarking/blob/master/GOVERNANCE-draft.md

2) Discuss/Confirm scope we want to tackle
     - define end goal

3) Identify initial next steps, starting ideas are:
     - develop list of candidate benchmarks
     - Having Yang take us through ACME air for Node

**Comment by yosuke-furukawa** [comment]
Sorry. My condition is not so good... I would like to attend this meeting but the meeting time is at 3 a.m. in Japan. I need to take a sleep to recover my condition.

But I would like to write my motivation for this benchmarking WG.

- **Continuous benchmark:** We should take a bench performance on every release continuously.
- **Graph:** And we should draw some graphs to detect performance down easily. e.g. http://arewefastyet.com/ And Thlorenz benchmark graph is extremely good. https://github.com/thlorenz/benchgraph
- **Fix benchmark tests:** I would like to fix benchmark tests on Node.js v0.10, v0.12, io.js v1.x, v2.x. In my understanding, v0.12 and v1.x full benchmark don't work. 

I am sorry for absence ...

**Comment by mhdawson** [comment]
yosuke, thanks I'll make sure to add those to the discussion

**Comment by mhdawson** [comment]
Minutes from initial meeting

https://github.com/nodejs/benchmarking/blob/master/meetings/2015-05-27/minutes.md

**Comment by targos** [comment]
I think you need to use hangouts on air to have the recording feature
