### ISSUE TITLE
Benchmark working group meeting Week of July 6

### ISSUE THREAD

**Issue by mhdawson** [nodejs/benchmarking#10]
The next meeting will be planned for the week of July 5. The draft agenda is:

*  Review of discussion in issues opened (carried over)
*  Discussion of investigation by Trevor
*  Discussion of investigation by Michael

I'll send out the invite to the participants so far. If you want to be added to the invite just let me know

Doodle poll for those not on the core invite list:

http://doodle.com/x2dd7y6qdv3xbefv

**Comment by trevnorris** [comment]
For reference, I've left issues on:
- hapi: https://github.com/hapijs/hapi/issues/2614
- kraken-js: https://github.com/krakenjs/kraken-js/issues/393
- grunt: https://github.com/gruntjs/grunt/issues/1350
- gulp: https://github.com/gulpjs/gulp/issues/1118

Figured doing it that way was easier to track discussions on participation with the benchmarking wg. I'll accumulate updates for meeting notes.

**Comment by mhdawson** [comment]
From doodle poll looks like best day is Thursday July 9 at 1PM EST

Hangouts link for participants: https://plus.google.com/hangouts/_/hoaevent/AP36tYdteIdJO1mKQM2vhYFcFv0ykPwgcUNx7KqDo9CLROGD6ifKNg

Youtube link for those who just want to watch: http://www.youtube.com/watch?v=0D9Ea2FNStE

**Comment by mhdawson** [comment]
Link for google doc for minutes 

https://docs.google.com/document/d/1uwydmaVrf-xGSQtNHpt8iPs62cVBabegSXTHGrLR7cA/edit?usp=sharing

**Comment by mhdawson** [comment]
Minutes from meeting https://github.com/nodejs/benchmarking/blob/master/meetings/2015-07-09/minutes.md
