### ISSUE TITLE
Next benchmark meeting 

### ISSUE THREAD

**Issue by sathvikl** [nodejs/benchmarking#103]
Any thoughts on when should we have the next node.js meeting..

**Comment by mhdawson** [comment]
Good, point. Its been on my list for quite a while.  Nod sure why I did not catch the notification for this.

**Comment by mhdawson** [comment]
@nodejs/benchmarking google poll for next meeting time: https://doodle.com/poll/xevr65f6eb47k53q

**Comment by mhdawson** [comment]
Ok final time select May 18 at 5PM EST.  Will open issue to capture that.

**Comment by mhdawson** [comment]
Believe we can close this issue in favor of https://github.com/nodejs/benchmarking/issues/107
