### ISSUE TITLE
Node.js Community Benchmarking meeting 18 May 2017 - 5 PM EST>

### ISSUE THREAD

**Issue by mhdawson** [nodejs/benchmarking#107]
Who

@nodejs/benchmarking 

# When

From  https://github.com/nodejs/benchmarking/issues/103 5pm est Thursday May 18 2017

# Where

* link for participants: Will add 5 mins before start of meeting:https://hangouts.google.com/hangouts/_/ytl/BA05JnRNlaSPiUdCLxBGRitBNzHQS1L-I-ZbA4TgPrU=?eid=100598160817214911030
* For those who just want to watch: https://www.youtube.com/watch?v=HrCE5GM8c8Q
* youtube admin page: https://www.youtube.com/my_live_events?filter=scheduled

Google doc for minutes: https://docs.google.com/document/d/17VaVphf5mOcmF4gbpWkpCjmW5WCTAwrNWsJNtt5VaeE/edit?usp=sharing

# Agenda
- Stand up 
- Discuss adopting TSC participation guidelines
- Actions from last meeting
- Open issues review
- Other business

# Actions from last meeting

* Michael and Gareth to work on additional benchmarks as discussed above
* all - review https://github.com/nodejs/benchmarking/pull/63 so we can discuss again in the next meeting

**Comment by mhdawson** [comment]
https://hangouts.google.com/hangouts/_/ytl/BA05JnRNlaSPiUdCLxBGRitBNzHQS1L-I-ZbA4TgPrU=?eid=100598160817214911030

**Comment by mhdawson** [comment]
Minutes https://github.com/nodejs/benchmarking/pull/108

**Comment by mhdawson** [comment]
Issue for choosing a regular meeting time: https://github.com/nodejs/benchmarking/issues/109

**Comment by mhdawson** [comment]
Issue for session on configuring CI jobs: https://github.com/nodejs/benchmarking/issues/110

**Comment by uttampawar** [comment]
New issue to add Node-DC-EIS to the benchmark suite is opened at,
https://github.com/nodejs/benchmarking/issues/86

**Comment by mhdawson** [comment]
Minutes landed, closing
