### ISSUE TITLE
Set up a regular time for benchmarking WG meeting

### ISSUE THREAD

**Issue by mhdawson** [nodejs/benchmarking#109]
In the last meeting we agreed trying to find a regular time to meet would be good.

Doodle poll to try and find a time http://doodle.com/poll/ihkis7cnrqnmbwnp

@nodejs/benchmarking

**Comment by mhdawson** [comment]
@nodejs/benchmarking reminder to fill in availability, only 1 participant so far.

**Comment by mhdawson** [comment]
@kunalspathak, @kfarnung, @boingoing, @uttampawar in case you missed the origin ping.

**Comment by gareth-ellis** [comment]
Have been away for the last couple of weeks, I've replied based on "normal" availability, there may be exceptions on odd weeks.

**Comment by mhdawson** [comment]
@CurryKitten can you fill in your availability.  

Ignore the actual  dates, just the day of the week as we are trying to set up a recurring meeting.

**Comment by kunalspathak** [comment]
@mhdawson  - i have filled in my availability.

**Comment by mhdawson** [comment]
From the poll it looks like Mondays at 3 EST is about the best time.  It's a time that is not too late for those in Europe (8PM for England) and not too early for those on the east coast.  Lets start with that and we'll see how it works.  I'll set the next meeting for June 19th as I'm out next week.

**Comment by mhdawson** [comment]
Meeting, set done.
