### ISSUE TITLE
Setting up/configuration Benchmark CI jobs - working session

### ISSUE THREAD

**Issue by mhdawson** [nodejs/benchmarking#110]
As discussed in the last meeting, for those who want to help in setting up/configuring/maintaining the benchmarking jobs.

Some background to read: https://github.com/nodejs/build/blob/master/doc/process/jenkins_job_configuation_access.md

<s>Doodle for meeting time: https://doodle.com/poll/gh6b3g436h3pp6ub</s>
<s>Time selected as Thursday June 1 @ 3EST.  </s>

New doodle http://doodle.com/poll/t9kmpticv6h8gups 

Hangout link for the meeting: https://hangouts.google.com/hangouts/_/ytl/292aFCmtSYKHBfioM8U6SofgQWfBHCKt-oCOmpZVZYU=?eid=100598160817214911030

**Comment by mhdawson** [comment]
@nodejs/benchmarking so far nobodies completed the doodle yet
@kunalspathak, @kfarnung, @boingoing, @uttampawar

**Comment by kfarnung** [comment]
👍

**Comment by mhdawson** [comment]
Thanks @kfarnung.  I'll check if anybody else has filled in the doodle as of tomorrow morning and then see if we can set it as one of those times or need to try with a new doodle.

**Comment by gareth-ellis** [comment]
I would be interested but I think i'll struggle to join today. If there's a recording of the session available afterwards that would be good

**Comment by mhdawson** [comment]
I did want to get at least one of the people from Intel in the session as well as they seemed very interested in being included.  I still only see @kfarnung as having completed the doodle poll so I'll set up new one to try for next week.

**Comment by mhdawson** [comment]
New poll: https://doodle.com/poll/gh6b3g436h3pp6ub

**Comment by mhdawson** [comment]
@nodejs/benchmarking, @kunalspathak, @kfarnung, @boingoing, @uttampawar
new poll, please complete.

**Comment by kunalspathak** [comment]
Updated my availability.

**Comment by mhdawson** [comment]
Time selected as Thursday June 1 @ 3EST.  @kunalspathak, @kfarnung

**Comment by kunalspathak** [comment]
@mhdawson  - We just realized that we have a training on June 1st @ 3EST. @kfarnung  and me will not be available? Can we reschedule it? Sorry about that.

**Comment by mhdawson** [comment]
Sorry just saw this now, but will reschedule.

**Comment by mhdawson** [comment]
New doodle http://doodle.com/poll/t9kmpticv6h8gups @kunalspathak @kfarnung @nodejs/benchmarking

**Comment by mhdawson** [comment]
@uttampawar, @sathvikl   it would be good to get somebody from Intel participate if possible.

**Comment by mhdawson** [comment]
Based on doodle have set for 5:30 EST on Thrusday the 8th.    The poll was for 5-6 but I'm booked at 5:00 to 5:30, I'm also away next week so instead of delaying lets start at 5:30 at least to get a start.

I'll add the hangout just before the meeting starts at 5:30.   @kunalspathak @kfarnung @nodejs/benchmarking @uttampawar @gareth-ellis @uttampawar, @sathvikl

**Comment by mhdawson** [comment]
Link for the hangout https://hangouts.google.com/hangouts/_/ytl/292aFCmtSYKHBfioM8U6SofgQWfBHCKt-oCOmpZVZYU=?eid=100598160817214911030

**Comment by kfarnung** [comment]
We're trying to get into the Hangout, having technical difficulties.  Be there soon.

**Comment by mhdawson** [comment]
Session held, closing
