### ISSUE TITLE
Remove 7.x from nightly benchmark runs

### ISSUE THREAD

**Issue by mhdawson** [nodejs/benchmarking#115]
Now that version 8.x is out, remove 7.x from the nightly runs/benchmarks.

**Comment by kfarnung** [comment]
I'll take a stab at this.

**Comment by mhdawson** [comment]
@kfarnung thanks.

**Comment by kfarnung** [comment]
Per meeting, change color for 8.x to match 7.x once removed.

**Comment by kfarnung** [comment]
Opened PR #117 

@mhdawson Is there an additional work item to disable 7.x benchmark runs in Jenkins?

**Comment by mhdawson** [comment]
Just need to turn off the schedule and then delete the job.  I'll do that one the PR lands and is tested.

**Comment by mhdawson** [comment]
Job deleted, closing.
