### ISSUE TITLE
Install clang on benchmarking machine

### ISSUE THREAD

**Issue by kunalspathak** [nodejs/benchmarking#116]
I was trying the benchmarking CI job to gather performance numbers for `node-chakracore` and currently it is blocked because `clang` is not installed. Can we install `clang` on the benchmark machines? 

I thought https://github.com/nodejs/build/pull/735/ would have addressed it, but looks like the ansible script changes doesn't install clang.

cc - @joaocgreis

**Comment by joaocgreis** [comment]
I did not include Clang in the Ansible script to avoid any possible interference with node-v8. We have a good download-and-cache script, in the beginning of chakracore-test-linux, and I'm trying to use that everywhere.

If I understand it correctly, you duplicated the benchmark job to benchmark-footprint-master-chakracore, so you can just copy the beginning of chakracore-test-linux to setup the environment for what is still chakracore specific.

**Comment by kunalspathak** [comment]
Thanks @joaocgreis . I will give it a shot and see if it helps.

**Comment by kunalspathak** [comment]
@joaocgreis  - Can you please review [these](https://ci.nodejs.org/job/benchmark-footprint-master-chakracore/jobConfigHistory/showDiffFiles?timestamp1=2017-06-19_10-03-35&timestamp2=2017-06-21_12-53-24) changes in the CI job to make sure that I added the build steps correctly? Before I trigger the run, I just want to make sure that this won't spoil the existing environment on that machine.

**Comment by joaocgreis** [comment]
@kunalspathak those were the correct changes to port, but I see some issues:
- Each `Execute shell` block in jenkins will be a separate bash instance. So, environment variables won't propagate from one to the next (unless explicitly saved and injected). You have to add the changes in the same `Execute shell` block that needs them.
- In the chakracore job we use the git plugin, and it is configured to clean the folder on the beginning of each run. I see in the benchmark job you use git explicitly without the plugin, so you have to clean the folder manually. Adding this in the beginning should work: `rm -rf cmake-* clang+llvm-* make-* || true`
- I don't know if the benchmark machine has ninja installed, beware that using ninja might fail. Note that the changes you copied here try to set up ccache. If ccache is found, only the first build will be slow, ninja will make little difference for the next ones.

**Comment by kunalspathak** [comment]
> You have to add the changes in the same Execute shell block that needs them.

Ah, didn't know that. Thanks for the pointers.
> I see in the benchmark job you use git explicitly without the plugin, 

I am following the convention of other benchmarking CI job and didn't prefer to add anything extra in configure step for chakracore job.

> Adding this in the beginning should work: rm -rf cmake-* clang+llvm-* make-* || true

I prefer not removing these tools (unlike folders which we delete) unless you have a strong reason to remove other than normal cleanup. 

>  I don't know if the benchmark machine has ninja installed,

No, it is not. i will remove the ninja flag given the fact we already use `cccahe`.

I have updated the job configuration. Let me know how it is.

**Comment by joaocgreis** [comment]
You need to begin the script with `#!/bin/bash -ex`, right in the first line, to make it use bash instead of dash. It was not there before, but should not be a problem to add. Other than that LGTM.

About not removing the folders: I don't think that'll be a problem. We could even change the script to take advantage of this, but I don't think it's worth maintaining a different script, at least for now. If the job works on the first run but fails the second, this is probably the cause, you can add the `rm` then.

**Comment by kunalspathak** [comment]
Thanks @joaocgreis . I was able to run the job without problem. I was just wondering if some one can tell me the specs of the benchmarking machine. May be @jbergstroem?

**Comment by kunalspathak** [comment]
I was able to successfully trigger different runs on the machine to make sure that environment setup made by chakracore doesn't spoil other benchmarks run.

`benchmark-footprint-master-chakracore` run : https://ci.nodejs.org/job/benchmark-footprint-master-chakracore/15/
`benchmark-footprint-master` run : https://ci.nodejs.org/job/benchmark-footprint-master/625/
