### ISSUE TITLE
Benchmarking WG meeting - July 3 - cancel ?

### ISSUE THREAD

**Issue by mhdawson** [nodejs/benchmarking#119]
Due to the Canada Day long week, I'm not going to be around on July 3. I suspect many of our US participants wil also be away due to the July 4th holiday in the US.

Should we just cancel this instance ?

**Comment by AnilKumarRajput** [comment]
Yes , that will be fine . Thanks

**Comment by kunalspathak** [comment]
Sounds good to me.

**Comment by mhdawson** [comment]
Will setup meeting for next regularly scheduled time which is July 17.
