### ISSUE TITLE
Benchmarking meeting Monday July  17 2017

### ISSUE THREAD

**Issue by mhdawson** [nodejs/benchmarking#122]
@nodejs/benchmarking 

# When

 Monday July  17, 3 EST.  (7PM UTC)

# Where

* link for participants: https://hangouts.google.com/hangouts/_/ytl/cJ9wAwnbE0-1k_NV_DghKaoktVn_T_StMnGnzDW3LDg=?eid=100598160817214911030

* For those who just want to watch: https://www.youtube.com/watch?v=m2w_y-iMBYA
* youtube admin page: https://www.youtube.com/my_live_events?filter=scheduled

* Google doc for minutes: https://docs.google.com/document/d/1HMUImvOJLw5YfL9iuBXp7tE9U68bQzqj86MEMNdjFR0/edit

# Agenda
- Stand up 
- Actions from last meeting
- Open issues review
- Other business

# Actions from last meeting

* Kunal to create PR to add mean (or something else) to Acme air runs.
* Kunal to follow up on clang issue that is blocking Chakra core Acme air runs.
* Uttam is going to submit PR with info/scripts for DC-EIS
* Michael to suggest updated wording for participation guidelines

**Comment by gareth-ellis** [comment]
Am not going to be able to make it tonight.

*Had a go at getting an enviromment going running ubuntu 16.04 to recreate variable performance seen in #120 , however don't have a machine that I can get ubuntu running on and be able to generate meaningful data.

**Comment by mhdawson** [comment]
https://hangouts.google.com/hangouts/_/ytl/cJ9wAwnbE0-1k_NV_DghKaoktVn_T_StMnGnzDW3LDg=?eid=100598160817214911030

**Comment by mhdawson** [comment]
@kunalspathak @kfarnung @uttampawar you going to join ?

**Comment by mhdawson** [comment]
So far its just me so I'll wait about 5 minutes longer.

**Comment by mhdawson** [comment]
Ok, it was just me on the call today so I think we'll cancel until the next time in 2 weeks.

**Comment by kunalspathak** [comment]
Sorry Michael, I thought the meeting was at 5PM EST as usual. I didn't have much to share in this meeting as was busy in other activities.

**Comment by sathvikl** [comment]
@mhdawson I thought it was on the 19th. Can we reschedule it for this month since no one was able to join.. ?!

**Comment by uttampawar** [comment]
@mhdawson I missed it as well due to wrong calendar entry.
