### ISSUE TITLE
Meeting at NodeConf EU '17 to discuss Node.js performance

### ISSUE THREAD

**Issue by bmeurer** [nodejs/benchmarking#124]
I'd like to propose some kind of informal meeting at NodeConf EU in November to discuss various aspects of Node.js performance, specially how to track performance and how to prioritize potential work items. One of the main items here is obviously the need for benchmarks, ideally a standardized benchmark suite that is representative of common JavaScript workloads on the Node.js side.

Background here is that for V8 it's currently difficult to properly include Node.js concerns when it comes to planning around performance optimizations. Similarly the lack of a standard benchmark suite made it difficult for Node.js to decide on whether or not to use a certain V8 version for a given Node.js release (as we've experienced with Node 8 and V8 5.8 to 6.1 now).  Being able to plan in advance and properly include important concerns for Node.js use cases would reduce the pain for everyone significantly, and I think an in-person meeting would help a lot here.

I'll be at NodeConf EU together with @psmarshall, who's been working a lot on Node.js performance recently.

**Comment by mcollina** [comment]
If we want this conversation happening, I think we can make a room available for the meeting.

**Comment by bmeurer** [comment]
@jaro-sevcik from the V8 compiler team is also going to join.

**Comment by mhdawson** [comment]
I'm going to be at NodeConfEU and Arunesh will be there but none of the other benchmarking WG members will be that we know of.  Node Interactive might be better but those on the last call are still not sure.

I'm thinking we should set up an on-line meeting to get started on discussion.  I'm out next week so how about we send out a doodle for the week of Aug 21st.

**Comment by bmeurer** [comment]
I'm on vacation that week, but maybe we can do it the week after?

**Comment by kunalspathak** [comment]
People who are interested, please share your availability in week of August 28th at https://doodle.com/poll/byewa29dzkmx8xf3

**Comment by bmeurer** [comment]
Thanks for setting up the Doodle. Unfortunately none of the time slots work for me currently.

**Comment by kunalspathak** [comment]
What are the times you are available? I will include those as well in the doodle.

**Comment by bmeurer** [comment]
How about adding 6AM / 9AM / 11AM Europe/Berlin to the Doodle?

**Comment by kunalspathak** [comment]
Updated.

**Comment by mhdawson** [comment]
@bmeurer any chance you could make the next regular benchmarking meeting which is  August 28 at 3 EST, 7 UTC ?  It would be good to get some of you as regular attendees for the benchmarking WG meetings.

**Comment by bmeurer** [comment]
I guess so, yes. Is that 8:00 CET or 20:00 CET?

**Comment by gareth-ellis** [comment]
21:00 CET (CET is currently UTC+2)

**Comment by bmeurer** [comment]
Ok, I'll join tomorrow. What's the Hangout id?

**Comment by kunalspathak** [comment]
@mhdawson will publish it in #134

**Comment by mhdawson** [comment]
@bmeurer hangout id has been added to the issue for the meeting. Sorry I just opened it today.  It is: 
https://hangouts.google.com/hangouts/_/ytl/n2RXGmmz6beAsiuZwuNL_YDoNjjD37o5pr6CARiLDhY=?eid=100598160817214911030

**Comment by bmeurer** [comment]
Thanks.

**Comment by mhdawson** [comment]
@bmeurer is now attending our bi-weekly meeting so I think we can close this.  Please let me know if that is not the case.
