### ISSUE TITLE
Benchmarking WG Meeting Aug 1 - 3 EST

### ISSUE THREAD

**Issue by mhdawson** [nodejs/benchmarking#125]
@nodejs/benchmarking 

# When

 Monday Aug 1, 3 EST.  (7PM UTC)

# Where

* link for participants: https://hangouts.google.com/hangouts/_/ytl/4MkG7WfxCKJLv5GaZNoaRlnN8UWnOtHczW9lpB8u9wU=?hl=en_US
* For those who just want to watch: https://www.youtube.com/watch?v=AuFtg1LIP1w&feature=youtu.be
* youtube admin page: https://www.youtube.com/my_live_events?filter=scheduled

* Google doc for minutes: https://docs.google.com/document/d/1LY7BKg0HkioumbP29gUw9OtW07I1nglimRgnz3S0VP4/edit

# Agenda
- Stand up 
- Actions from last meeting
- Open issues review
- Other business

# Actions from last meeting

* Kunal to create PR to add mean (or something else) to Acme air runs.
* Kunal to follow up on clang issue that is blocking Chakra core Acme air runs.
* Uttam is going to submit PR with info/scripts for DC-EIS
* Michael to suggest updated wording for participation guidelines

**Comment by mhdawson** [comment]
Due to a family emergency I cant make it today. Either you can meet without me or we can try for tomorrow. Please comment on issue as what we should do.

**Comment by gareth-ellis** [comment]
Pushing out till tomorrow is fine with me

**Comment by kunalspathak** [comment]
Tomorrow should be fine.

**Comment by kunalspathak** [comment]
@uttampawar - if possible for you, can you join tomorrow's meeting to discuss about onboarding node-dc-eis?

**Comment by mhdawson** [comment]
Ok, I'll do my best to be available 3 EST on Tuesday.

**Comment by mhdawson** [comment]
Link for participants: https://hangouts.google.com/hangouts/_/ytl/4MkG7WfxCKJLv5GaZNoaRlnN8UWnOtHczW9lpB8u9wU=?hl=en_US

**Comment by mhdawson** [comment]
Seems like I had the wrong link for viewing, just updated now
https://www.youtube.com/watch?v=AuFtg1LIP1w&feature=youtu.be

Sorry for those that wanted to watch live, but the updated link at least has the video that can be watched afterwards.

**Comment by uttampawar** [comment]
@kunalspathak  Yes, I'll be joining today's meeting.

**Comment by uttampawar** [comment]
It looks like I got the calendar entry wrong again. ;-(

**Comment by mhdawson** [comment]
PR for minutes https://github.com/nodejs/benchmarking/pull/129
