### ISSUE TITLE
Getting the first benchmark running 

### ISSUE THREAD

**Issue by mhdawson** [nodejs/benchmarking#13]
From discussion in last benchmarking meeting 

+ when we would run minimal/minimal sets
+  how to use same H/W across runs

Next steps
+ sync with build workgroup to get their feedback on how to address H/W issue
+ put together outline of what we want to do, then ask foundation members for h/w

**Comment by mhdawson** [comment]
I was out 2 weeks ago and the meeting for the build workgroup was cancelled this week.  Will bring up in next meeting (July 27)

**Comment by mhdawson** [comment]
Feedback from build workgroup was that IBM had offered softlayer resources in the past.

I've now connected with the right people and can add softlayer resources, initial hardware to be added is being discussed here:  https://github.com/nodejs/benchmarking/issues/18

Next steps will be to:
  1) jenkins jobs to run acme air running
  2) jenkins jobs to run benchmarks that are part of Node build

We should also discuss if we want/need to ask Foundation members for any other hardware.

**Comment by mhdawson** [comment]
Have temporarily setup jobs to push to here http://nodejs.devrus.com:8080/ until we can get the same as part of nodejs.org.

* cronjob on benchmark machines pushes updated charts nightly (as opposed to pull which is planed for node webiste)
* repo is pulled every 15 mins to update www content

It shows the data for the benchmarks we currently have running.

**Comment by mhdawson** [comment]
Ok data is available on benchmarking.nodejs.org

**Comment by ofrobots** [comment]
@mhdawson: For me http://benchmarking.nodejs.org redirects to the main website.

**Comment by gareth-ellis** [comment]
@ofrobots I saw that once or twice to start with too - I've worked out what it is

You need to goto https://benchmarking.nodejs.org - rather than just http.

Would be good we could have it that either works, or that http redirects to https....
