### ISSUE TITLE
Benchmarking jobs failing

### ISSUE THREAD

**Issue by mhdawson** [nodejs/benchmarking#130]
Started failing Aug 10.

 https://ci.nodejs.org/view/Node.js%20benchmark/job/benchmark-footprint-8.x/

**Comment by gareth-ellis** [comment]
Looks like an issue with posting the results, first benchmark passes but posting result returns nothing instead of ok.
Issue with machine itself?

**Comment by mhdawson** [comment]
Looks like it is failing to post to benchmark data machine:

+ RESULT=17485824
+ echo RESULT: 17485824
RESULT: 17485824
+ export BENCHID=1
+ /home/iojs/benchmarking/tools/postResults/postit.sh 6 1 17485824
+ PUBLISH_RESULT=
+ [  != ok ]
+ exit -1
/tmp/hudson5618630606784231468.sh: 40

**Comment by mhdawson** [comment]
Bridge was not running, restarted. From uptime looks like machine was rebooted 5 days ago, really need to get to setting up so the bridge auto starts.

Kicked off run to check if issue is resolved, but job is waiting on v8 test jobs to run first.

**Comment by mhdawson** [comment]
First run was ok, kicking off runs on other versions.  Will close once we see passes on all four.

**Comment by mhdawson** [comment]
All green again closing.
