### ISSUE TITLE
Issues with benchmarking runs

### ISSUE THREAD

**Issue by gareth-ellis** [nodejs/benchmarking#133]
Hello,

I got a notification that @mcollina 's benchmark run for a PR failed, it seems as if something may have "cleaned up" the machine during the run - i tried to relaunch with a filter to retry the last benchmark it was running to verify no issue with the benchmark itself, but Jenkins doesnt seem to be adding anything to the queue.

I saw as well that the Node DC had been running for 21 hours, it seemed to have tried to stop itself but there was a syntax error in the stop command. As such, the benchmark machine didnt complete its nightly runs.

I stopped the current job, so it should make its way through the rest of the queue now.
fyi / @mhdawson @uttampawar @kunalspathak

**Comment by mhdawson** [comment]
The most recent benchmark jobs also failed.

**Comment by mhdawson** [comment]
Killed the process that was still running on the machine and now builds seem ok.

**Comment by uttampawar** [comment]
@kunalspathak @mhdawson Current scripts work fine on my local machine for Node-DC but it seems to having problem on the test machine. How do I debug it without access to the machine? This workload should not take more than 10-15 minutes. Can we get together for 30 minutes to discuss this issue?

**Comment by kunalspathak** [comment]
Looking at the logs from recent runs, it looks like it gets stuck while starting the mongodb. Is that right? I see that you use custom port `28000` in your script. Could you just use same script we use for acmeair monogodb?

**Comment by uttampawar** [comment]
@kunalspathak @mhdawson I made those changes which seems to be working fine on the local machine. Is this would be a good time to try on the benchmarking machine? I don't want to cause any issue due to this run?

**Comment by kunalspathak** [comment]
I don't see anything running right now, so go ahead and kick the run. But if you see it is stuck again, just abort the job.

**Comment by mhdawson** [comment]
I tried running today and it seemed to get stuck.  Looking in the logs for the step starting mongo I see:

```
/home/iojs/build/workspace/benchmark-node-dc-eis/benchmarking/experimental/benchmarks/node-dc-eis/mongodb.sh: line 21: mongod: command not found
```

**Comment by mhdawson** [comment]
This was the job I ran 

https://ci.nodejs.org/view/Node.js%20benchmark/job/benchmark-node-dc-eis/5/console

You can see it stopping once I killed off the processes.

**Comment by mhdawson** [comment]
I'll see if I can figure out why it can't find mongod

**Comment by gareth-ellis** [comment]
perhaps can close this now?

**Comment by mcollina** [comment]
@gareth-ellis 👍 . I've restarted another job, let's see how it goes.

**Comment by mcollina** [comment]
Closing, this is working now.
