### ISSUE TITLE
Bencharking WG Meeting - Aug 28 - 3 EST

### ISSUE THREAD

**Issue by mhdawson** [nodejs/benchmarking#134]
@nodejs/benchmarking 

# When

 Monday Aug 28, 3 EST.  (7PM UTC)

# Where

* link for participants: https://hangouts.google.com/hangouts/_/ytl/n2RXGmmz6beAsiuZwuNL_YDoNjjD37o5pr6CARiLDhY=?eid=100598160817214911030
* For those who just want to watch: https://www.youtube.com/watch?v=78Vvc7OqhME
* youtube admin page: https://www.youtube.com/my_live_events?filter=scheduled

* Google doc for minutes: https://docs.google.com/document/d/1hFUVp1QSNjHI8Ut9E0CRYLK3_11YHq8CrFFeuaP-rac/edit?usp=sharing

# Agenda
- Stand up 
- Actions from last meeting
- Open issues review
- Other business

# Actions from last meeting
* Michael to suggest updated wording for participation guidelines
  * Still need to do this, roll over.
* Kunal will open an issue in the repo to track adding mean or something like that to Acme air
   Runs.
   * https://github.com/nodejs/benchmarking/issues/132 

# Issues review

### nodejs/benchmarking

* Status of running node core benchmarks [#127](https://github.com/nodejs/benchmarking/issues/127)
* New script to run Node-DC-EIS workload  [#123](https://github.com/nodejs/benchmarking/pull/123)

### nodejs/build

* Install of Rscript on new benchmarking machines [#821](https://github.com/nodejs/build/issues/821)

**Comment by mhdawson** [comment]
Starting  hangout now.

**Comment by mhdawson** [comment]
https://hangouts.google.com/hangouts/_/ytl/n2RXGmmz6beAsiuZwuNL_YDoNjjD37o5pr6CARiLDhY=?eid=100598160817214911030

**Comment by sathvikl** [comment]
@mhdawson  what's the link to join ?

**Comment by mhdawson** [comment]
Just added.

**Comment by mhdawson** [comment]
PR for minutes: https://github.com/nodejs/benchmarking/pull/137
