### ISSUE TITLE
Survey questions for end users to decide what to benchmark

### ISSUE THREAD

**Issue by mhdawson** [nodejs/benchmarking#136]
Generate list of questions, then work with community committee to see if we can send out survey from Node.js Foundation/community.

@bmeurer will come up with some initial ideas.

**Comment by bmeurer** [comment]
You got the wrong handle.

**Comment by mhdawson** [comment]
@bmeurer sorry about that.

**Comment by bmeurer** [comment]
Here's a preliminary list of bullet points:

- What is your primary use case for Node? (Web Developer Tooling / Standalone Servers / Cloud Services / Others)
- What kind of language dialect do you use? (ES5 / ES6 / ESNext whatever supported by most recent Node version / TypeScript / Other)
- Do you run *optimization passes* on your JavaScript before you deploy it to Node? (Minification / Bundling / Obfuscation / Other) 
- What's your preferred way to write asynchronous code? (Callbacks / Promises / async/await / Other)
- What are the top 5 Node modules that you use most often?
- If you could choose which JavaScript language feature should be optimized next, what would that be? Using the latest Node release as the basis.

Mostly WIP at this point, and targeted towards figuring out what JavaScript focused benchmarks are needed. That doesn't really say a lot about the other performance aspects of Node.

**Comment by bmeurer** [comment]
There was already a survey run earlier this year, which might be related, results were published [here](https://hackernoon.com/node-js-emerging-as-the-universal-development-framework-for-a-diversity-of-applications-c2e788290f5f).

**Comment by mcollina** [comment]
We are missing a good framework in the ecosystem to microbenchmark I/O operations with statistic significance. Something similar to what we have in core, but something we can use to measure promises, callbacks, database drivers. I had several shot at this, none of them was great.

A typical question I get is: "how do async/await stack up against callbacks".

Some folks (including myself) have been putting some time in https://github.com/fastify/benchmarks. This is not comprehensive, but the various frameworks do more or less the same things.

**Comment by mhdawson** [comment]
What is your primary use case for Node? (Web Developer Tooling / Standalone Servers / Cloud Services / Others)
What kind of language dialect do you use? (ES5 / ES6 / ESNext whatever supported by most recent Node version / TypeScript / Other)
Do you run optimization passes on your JavaScript before you deploy it to Node? (Minification / Bundling / Obfuscation / Other)
What's your preferred way to write asynchronous code? (Callbacks / Promises / async/await / Other)
What are the top 5 Node modules that you use most often?
If you could choose which JavaScript language/Node.js feature should be optimized next, what would that be? Using the latest Node release as the basis.

**Comment by mhdawson** [comment]
Opened request for help sending out survey https://github.com/nodejs/community-committee/issues/153

**Comment by mhdawson** [comment]
Survey is live here: https://www.surveymonkey.com/r/NodeBenchmarking

**Comment by mhdawson** [comment]
We have a dump of the responses so far.  I'm not going to post them here as I believe we should wait for the poll to close before we make the results public in order to avoid influencing the results.  If members of the @nodejs/benchmarking team would like a copy just let me know and I'll send them on through email.

**Comment by bmeurer** [comment]
@mhdawson Can you send me a copy of the responses so far?

**Comment by mhdawson** [comment]
@bmeurer I realized some data might have to be stripped out (for example any identifying info) and have just asked the question I should have asked before which is if any of the data is sensitive.  Of course we'll need to share with benchmarking team but I want to agree with the Foundation contact doing the survey how/what we should share.  It may take me a bit more time to do that.

**Comment by mhdawson** [comment]
Closing since the survey is complete and we are just waiting for the final data from the user-feedback team.
