### ISSUE TITLE
jsperf-like tool for benchmarking node.js/io.js

### ISSUE THREAD

**Issue by mscdex** [nodejs/benchmarking#14]
**Background:** A couple of weeks ago I was working on performance again for my js http parser, especially with the newer v8 versions that have been released (or are in the pipeline) since I first started working on the parser. Typically I would just use Chrome and jsperf.com, but I noticed that jsperf.com had been down for some time (with no public time table if/when it will be back up) and I needed an equally easy way to do benchmarking. So I took it upon myself to sit down and write something.

The repo for the tool can be found [here](https://github.com/mscdex/benchd). It allows you to run benchmarks (using a slightly modified version of [benchmark.js](https://github.com/bestiejs/benchmark.js/) to work better with node/io.js) against one or more versions of node.js/io.js (v0.8+) from the browser. The project still has a few items on the TODO, but it is in a mostly working state right now and I have been using it locally for the past few days. One thing that I did discover is that the "vanilla" mode, which uses the `vm` module to execute benchmarks, may not be as useful when comparing across different node.js/io.js versions because the numbers/trends do not always match that of results under non-"vanilla" mode. That's just something to be aware of if you're trying things out.

I'm not sure if this tool will be of much use for this WG or not, but it was suggested that I post here about it. If people are interested in it, feel free to send some PRs and create issues for bugs and feature requests. :-)

**Comment by targos** [comment]
Do you think it is stable enough to publish to npm? I'd like to try it and the readme says `npm install -g benchd`

**Comment by mscdex** [comment]
@targos I'd like to at least get some tests in yet and improve the frontend error handling a bit more. I don't know when exactly that will be done, but my hope is to publish the first version by sometime this weekend at the latest.

**Comment by DavidTPate** [comment]
@mscdex Any luck on getting this published?

**Comment by mscdex** [comment]
@DavidTPate Unfortunately I haven't had time to work on it anymore since I last commented. I haven't forgotten about it though...

**Comment by mscdex** [comment]
Alright so I just decided to publish what I already have (after fixing a couple things) for v0.0.1. WebSocket error handling still needs to be improved and tests still have to be written though.

**Comment by trevnorris** [comment]
Is this supposed to run benchmarks on the server then display the results in the browser?

**Comment by mscdex** [comment]
@trevnorris Yes.

**Comment by mhdawson** [comment]
I think this can be closed, referenced tool was updated a while back and not since then so WG is aware  and will keep in consideration as we move forward.
