### ISSUE TITLE
Next Benchmarking meeting 

### ISSUE THREAD

**Issue by mhdawson** [nodejs/benchmarking#16]
Draft agenda is:

+ Review actions from last meeting

+ Corbin to give team a deep dive on - https://github.com/corbinu/docker-demos  (may be removed as Corbin did not respond to doodle)

+ Review proposal of what we want to do requesting hardware

+ Review of discussion in issues opened 

+ Getting the first benchmarks running

+ Update from Michael on minimal Acme Air for builds

I'll send out the invite to the participants so far. If you want to be added to the invite just let me know

Doodle poll: http://doodle.com/mwbrt5s7sq2ydstm

I'll include everybody on the core list. If you want to be added just let me know.

**Comment by trevnorris** [comment]
Sorry I didn't respond. This last month has been unusually busy for me.

**Comment by mhdawson** [comment]
There have been only 3 responses to the doodle.  I think I better send out another one to see if we can find a better time with more participation

**Comment by mhdawson** [comment]
New doodle poll http://doodle.com/8afhctmstaksaa4s

**Comment by rvagg** [comment]
FYI there is a tickbox you can check when setting up a doodle to make it timezone-adaptive, when I view that doodle it's meaningless to me because of this.

**Comment by trevnorris** [comment]
Has the time zone thing changed? I just filled it out from my phone assuming it was adapted.

**Comment by mhdawson** [comment]
I looked at the poll and I can't seem to find how to change it for an existing poll.  I see the link when creating a new poll but I can't find the same poll for an existing option.  The times were in EST.  

Should I cancel this poll and send out a new one ?

**Comment by mhdawson** [comment]
Link to new doodle updated to reflect EST times - http://doodle.com/gee8ckrsh6tk92zu

**Comment by mhdawson** [comment]
Based on doodle set meeting time as Sep 30 at 2pm EST.  Will send out google hangout and reminder a day ahead as well as adding to this issue.

**Comment by mhdawson** [comment]
Links for meeting tomorrow:

https://plus.google.com/hangouts/_/hoaevent/AP36tYdSJkS2lHogfpcrbWUP-VfMtWqHH2GxIukizkAPfkb3yNk6Ew

Hangouts on air for participants

Link for those who just want to watch: http://youtu.be/IC6AMOfEeL4

Doc for agenda/minutes: https://docs.google.com/document/d/1GWTKPECTTjlMy2U3ERmcIsS236YCRnoyaSd8zYIIo3Y/edit

**Comment by mhdawson** [comment]
Sorry was not able to start the meeting recording as for some reason I had no "start recording" button.  Its worked before and I saw it after the meeting ended so either I was blind and missed it or there was a temporary issue that prevented it from being available at the start of the meeting.

**Comment by mhdawson** [comment]
Minutes posted here https://github.com/nodejs/benchmarking/blob/master/meetings/2015-09-30/minutes.md
