### ISSUE TITLE
Joining the benchmarking team

### ISSUE THREAD

**Issue by choskim** [nodejs/benchmarking#160]
@mhdawson, @MylesBorins said to contact you about me potentially joining the team. Do you have time to chat?

**Comment by mhdawson** [comment]
Sure, lets find a time this week.  Would 3 EST on Thrusday work for you ?

**Comment by choskim** [comment]
@mhdawson, that works for me. I'll send you my contact info to the email address on your Github profile.

**Comment by mhdawson** [comment]
Sounds good will call you then.

**Comment by mhdawson** [comment]
We've talked today.  Looking forward to seeing @choskim at the meeting next Monday.  Closing.
