### ISSUE TITLE
Run benchmarks with the latest canary build

### ISSUE THREAD

**Issue by targos** [nodejs/benchmarking#177]
I think it would be quite interesting to see where the canary branch is in the benchmark graphs @ https://benchmarking.nodejs.org/

**Comment by mhdawson** [comment]
Is the branch to build canary-base ?

**Comment by targos** [comment]
No, it is canary in nodejs/node-v8: https://github.com/nodejs/node-v8/commits/canary

**Comment by mhdawson** [comment]
Create job to run on that branch. https://ci.nodejs.org/view/Node.js%20benchmark/job/benchmark-footprint-canary/1/console

If that runs ok, then last step would be to edit the configs to add canary to the data included on the charts @bmeurer any chance you could do a PR for that ?

**Comment by mhdawson** [comment]
Had to do small fixup, but second one ran ok, kicked off second run so we'll have minimum 2 data points required by the charts.  Job is now setup to run nightly.

**Comment by targos** [comment]
The job is running daily and https://github.com/nodejs/benchmarking/pull/178 landed. What else is needed?

**Comment by mhdawson** [comment]
We need a PR that updates the configuration for the charts to include canary.  Ex: 
https://github.com/nodejs/benchmarking/blob/master/benchmarks/dc_eis_throughput/dceisThroughput.json

```json
{
 "benchid": 11,
 "name": "node-dc-eis Ops/s[higher is better]" ,
 "template": "../common/common_template1.html.base",
 "units": "ops/s",
 "outputBase" : "dceis_throughput",
 "streams": [ {"streamid": 1, "name": "master", "color": "blue" },
              {"streamid": 2, "name": "4.x", "color": "red" },
              {"streamid": 4, "name": "6.x", "color": "DarkMagenta" },
              {"streamid": 6, "name": "8.x", "color": "grey" }
            ],
 "enabled": true
}
```

Needs to be updated to include the canary data.

This needs to be done for every benchmark config json.

The hardest part may be finding a color that looks reasonable.

**Comment by targos** [comment]
Proposition: https://github.com/nodejs/benchmarking/pull/182

**Comment by targos** [comment]
And it's done, thank you all!

**Comment by mhdawson** [comment]
@targos good choice of color, thanks for getting this done :)
