### ISSUE TITLE
Bare metal machine for initial benchmark runs

### ISSUE THREAD

**Issue by mhdawson** [nodejs/benchmarking#18]
I have gotten a softlayer account that I plan to use to bring a bare metal machine into the Node community CI for running the benchmarks.

I'm thinking of starting with a low end machine which is an 
E3-1270 (4 cores, 3.4Ghz) with 4G ram and 500G disk running Ubuntu 14

I believe it should be enough to run acme air in a regression test configuration.

I'm creating this issue to see if people think that size machine is a good place to start or if we think we might need more ram/cores/disk to start.

If I don't hear otherwise I'll plan to look at bringing on the machine.

**Comment by obastemur** [comment]
I don't know if there is a plan to masure IO performance. IMHO, SSD provides more consistent read and write speed.

**Comment by seabaylea** [comment]
@mhdawson that should be enough for a simple AcmeAir config, if we bind the three components (JMeter load driver, AcmeAir app and MongoDB) so a single processor.

**Comment by rmg** [comment]
@seabaylea do you mean restrict the node/libuv thread pool to a single core? Wouldn't that type of constraint make the results less meaningful?

**Comment by mhdawson** [comment]
SSD is available but it will double the monthly cost of the machine so I'd only want to add it if we really feel it is necessary

**Comment by seabaylea** [comment]
@rmg It depends what we're trying to achieve with the particular test. Yes, it restricts Node/libuv's thread pool, but it removes variation in results from interactions with the JMeter driver or MongoDB - which might be the aim if its regression testing.

As its a 4 core machine, we could arguably bind to 2 CPUs.

**Comment by rmg** [comment]
@seabaylea sounds reasonable. Consistency between runs is definitely the most important factor. I guess I was worried more that the data leads us down some path where we optimize for a single core but deploy on multi-core.

Thinking about it more, we definitely need multiple physical cores so we don't mask any race conditions or other issues that only come up with "real" concurrency.

**Comment by mhdawson** [comment]
Added to the CI as https://ci.nodejs.org/computer/iojs-softlayer-benchmark/.  Seems like we got more than we asked for as the RAM ended up being 8G.

**Comment by mscdex** [comment]
I just noticed that PRs are not running on the `master` node anymore (since 10/8), but instead on the recently added `iojs-softlayer-benchmark` node. Was this unintentional?

**Comment by mhdawson** [comment]
Yes, it was not intended to move any other jobs over, although I'm also not sure its an issue. Will talk to Johan who setup the initial tags on the machine for me
