### ISSUE TITLE
New meeting time 

### ISSUE THREAD

**Issue by mhdawson** [nodejs/benchmarking#187]
@nodejs/benchmarking 

After talking to @bmeurer, to make it easier for some to attend I'm proposing we move the meetings so that we alternate between:

Monday 2 EST 
Tuesday 2 EST

Unless I hear any objections I'll move the next meeting.

**Comment by bmeurer** [comment]
That'd be awesome! 👍

**Comment by mhdawson** [comment]
Times updated, closing
