### ISSUE TITLE
Next Benchmarking Meeting

### ISSUE THREAD

**Issue by mhdawson** [nodejs/benchmarking#19]
Draft agenda is:

    Review actions from last meeting

    Review of discussion in issues opened

I'll send out the invite to the participants so far. If you want to be added to the invite just let me know

Doodle poll: http://doodle.com/poll/p52s8hfq4vbhp2ec

**Comment by trevnorris** [comment]
Unfortunate that the one time everyone else can go to is during the Foundation TSC meeting.

**Comment by mhdawson** [comment]
The 2 times I see everybody else being available is 1 PM EST ?  The TSC meeting is at 4 EST ?

**Comment by trevnorris** [comment]
Ah crap. And again I forget to change the time zone.

**Comment by mhdawson** [comment]
Ok Date set as Wed Oct 21 @ 1PM EST

Hangouts on Air for participants
https://plus.google.com/hangouts/_/hoaevent/AP36tYfUADYUqfJueFdPTz9ollMrBaIXucl6TVqykdp-rqZRsNhAfA

Events page : https://plus.google.com/events/c2em3ljcuu7o0dvl470qabv96t4


YouTube link for watch - http://youtu.be/TShCsXs2uvI

**Comment by ofrobots** [comment]
Unfortunately, I won't be able to make it this week.

**Comment by mhdawson** [comment]
Ended up just being myself and Seth so we decided to postpone and will send out a new doodle to find the new time

**Comment by mhdawson** [comment]
Link for new doodle poll http://doodle.com/poll/87h3z3atkmqzvydx

**Comment by mhdawson** [comment]
Sorry did not close on last poll in time

New poll

http://doodle.com/poll/6capy7r7qh49bdu9#admin

**Comment by mhdawson** [comment]
Date set as Nov 19 at 12:00 EST

**Comment by mhdawson** [comment]
Hangout for active participants: https://plus.google.com/hangouts/_/hoaevent/AP36tYfY-8R9qGcsBqX9CmVOQ0aGJS9VSweiY6npTATy66pUbGOBpA?hl=en

Link to watch: http://youtu.be/gSC82-VqeqE

Link to doc for minutes: https://docs.google.com/document/d/16TjMKdHlKGnfDTAXRo3YLKPnSI8-DwTl_ejqLcr68G8/edit

**Comment by mhdawson** [comment]
Minutes are here: https://github.com/nodejs/benchmarking/blob/master/meetings/2015-11-19/minutes.md
Recording:  http://youtu.be/gSC82-VqeqE
