### ISSUE TITLE
Issues with existing benchmark scripts

### ISSUE THREAD

**Issue by sathvikl** [nodejs/benchmarking#191]
I am adapting the run scripts written for acmeair.sh and [ run-dc-eis.sh](https://github.com/nodejs/benchmarking/blob/master/experimental/benchmarks/node-dc-eis/run-dc-eis.sh)
for ghost.js [run-ghost-js.sh](https://github.com/sathvikl/benchmarking/blob/add_ghostjs/experimental/benchmarks/ghost-bench/run-ghost-js.sh#L314)

I am trying to add a timeout functionality for the whole script, so Jenkins can reliably terminate all running scripts. 
However, there are cases like below, which continue to execute even after the on_exit function in the script has executed. 
For example: grep will run in a loop looking for files/directories that don't exist. 

https://github.com/nodejs/benchmarking/blob/eb9206dbe27c348af190129eabdd0d20fd71bf14/experimental/benchmarks/acmeair/run_acmeair.sh#L281

https://github.com/nodejs/benchmarking/blob/eb9206dbe27c348af190129eabdd0d20fd71bf14/experimental/benchmarks/acmeair/run_acmeair.sh#L174

Is there a cleaner way to achieve this ? 
My plan is to have:

```
function arg1 arg2
PID_function=$!
append PID_function to list of all the PIDs in the script. 
```

@gareth-ellis  @uttampawar  @mhdawson

**Comment by mhdawson** [comment]
@sathvikl could you add an additional check of another file that can be created as part of the on_exit function ?

**Comment by sathvikl** [comment]
@mhdawson  I don't quite understand. You mean to say, create those files so grep can exit?

**Comment by mhdawson** [comment]
Have the while check for an additional file X and terminate if it exists or the one it already checks.  Then have on_exit create the additional file X.

Having discussed in the benchmarking meeting, using the PIDs and a kill is probably the better solution.

**Comment by sathvikl** [comment]
I think this can be closed. 
Only this script will be updated: [run-ghost-js.sh](https://github.com/sathvikl/benchmarking/blob/add_ghostjs/experimental/benchmarks/ghost-bench/run-ghost-js.sh#L314)

**Comment by mhdawson** [comment]
Ok closing.

**Comment by sathvikl** [comment]
@mhdawson  I choose to use  `jobs -p` since it would reliably return all the PIDs of the background processes that have been launched from the script. 
[change in run-ghost-js](https://github.com/sathvikl/benchmarking/blob/add_ghostjs/experimental/benchmarks/ghost-bench/run-ghost-js.sh#L85)
This is a simple enough change that can be done on all the scripts OR better yet in Jenkins. 

The issue is that  `"PIDS = $! $PIDS" ` does not return the correct PID on many occasions. 
and if the called script calls yet another script, I would have go look for it.
