### ISSUE TITLE
Regressions in v4 - kraken/JSbench

### ISSUE THREAD

**Issue by gareth-ellis** [nodejs/benchmarking#20]
I periodically compare performance of Node releases with a variety of workloads to identify regressions over time.

In my measurements, I've identified a consistent regression between the v0.12 and v4 releases running the 'Kraken' and 'JSBench' suites

On kraken one of the worst individual metrics is imaging_desaturate where we see it running at around 45% of the speed that it ran on 0.12.

I see this on the community releases of node.

These numbers below are just collected on my laptop running a 64bit copy that i'd compiled locally:

0.12.7:
kraken.imaging_desaturate x 10.52 ops/sec ±3.90% (28 runs sampled)

v4.1.2:
kraken.imaging_desaturate x 6.76 ops/sec ±69.70% (25 runs sampled)
Hello,

I wasn't sure about the high variability above, so I increased the time allowed to run:
0.12.7:
kraken.imaging_desaturate x 5.66 ops/sec ±13.66% (549 runs sampled)
v4.1.2:
kraken.imaging_desaturate x 1.02 ops/sec ±10.11% (101 runs sampled)

Given the large number of changes between the two copies of node, profiles are a little tricky to follow, since there seems to be quite a different code path with take in v4 vs 0.12.7

It would be interesting to know firstly if anyone else runs these benchmarks, and if so if they're seeing similar regressions?

Source for my test:

```js
var	benchmark = require('benchmark')
  , benmkzoo = require('./lib/benmkzoo.js');
var suite = new benchmark.Suite;

var bm = new benchmark( benmkzoo.kraken['imaging_desaturate'] );
bm.options.maxTime=200;
bm.options.minCount=200;
suite.push(bm);
//add tests
suite
// add listeners
.on('cycle', function(event) {
  console.log(String(event.target));
})
.on('complete', function() {
  console.log('Fastest is ' + this.filter('fastest').pluck('name'));
console.log(this);
})
// run async
.run({ 'async': true , 'maxTime' : 200});
```

**Comment by seabaylea** [comment]
@mhdawson is this a candidate for tomorrow's agenda?

**Comment by gareth-ellis** [comment]
As a quick update, I now believe this to be down to v8. I had to rewrite the wrapper for kraken, as there was too many nodisms to be able to run on pure v8. I've tried running the benchmark on latest v8 too, which also seems to be regressed to the same sort of level. I'm currently narrowing down where the regression was introduced in v8.

Although this has turned out not to be a node issue, it's still affecting node performance. At this point I'm not sure if the regression in this benchmark is translating into something that would affect a user of node, however I'm going to continue investigating for the time being.

**Comment by gareth-ellis** [comment]
As discussed on the work group call yesterday It seems that the "regression"  is in 4.2.20 of v8.

If I back out the changes in hydrogen-instructions.cc and hydrogen-instructions.h 

i.e. these are the changes:

https://chromium.googlesource.com/v8/v8.git/+/4.2.20%5E!/#F26

https://chromium.googlesource.com/v8/v8.git/+/4.2.20%5E!/#F27

My results:

v8.4.2.19 	- 147286
v8.4.2.20 	- 111222
v8.4.2.19+hydro	- 110000
v8.v5 		- 103400 (latest from repo as of a few hours ago).

I've been using the octane benchmark harness (so higher = better), as the one we use by default with kraken contained  a lot of nodeisms, and I wanted to be running the same code when testing both node and v8, to ensure that the difference was in the engine and not the benchmark.

I've been using the image_desaturate.js workload only, as it was where I could reliably recreate the difference on node, and also on v8 from the relevant node versions. If required, I can supply the files for running this.

As you can see from my results, the current latest is still lower than 4.2.19 was - however as per Ali's comment in issue #25 this could well be misleading!

**Comment by gareth-ellis** [comment]
Closing as it's quite a while since this was raised, it's likely v8 has changed even more since the issue was spotted.
