### ISSUE TITLE
Failures on canary in DC-EIS

### ISSUE THREAD

**Issue by mhdawson** [nodejs/benchmarking#200]
Looks like DC-EIS is failing on the canary branch for the last few days:  

https://ci.nodejs.org/view/Node.js%20benchmark/job/benchmark-footprint-canary/73/

@uttampawar  can you take a look to see if you can recreate locally?

**Comment by targos** [comment]
It's probably this: https://github.com/nodejs/node/pull/18723

**Comment by mhdawson** [comment]
@uttampawar ping

**Comment by mhdawson** [comment]
@uttampawar ping

**Comment by uttampawar** [comment]
@mhdawson I'm not able to reproduce the error. Also, the 'ci' is not accessible.

**Comment by mhdawson** [comment]
It looks like whatever the problem was it is now resolved :)  Closing.
