### ISSUE TITLE
Next Benchmarking Meeting

### ISSUE THREAD

**Issue by mhdawson** [nodejs/benchmarking#21]
Draft agenda is:

+ Review actions from last meeting
+ Review of discussion in issues opened
+ review/discuss https://github.com/nodejs/benchmarking/issues/23

I'll send out the invite to the participants so far. If you want to be added to the invite just let me know

Updated doodle poll: http://doodle.com/poll/waab28wye22k92wi

**Comment by mhdawson** [comment]
Based on the doodle poll looks like we'll have good attendance for Thursday Jan 7 at 12:00 EST .  Sent out invite.  If you did not receive please send me the email I should use and I'll add you to my invite list.

Hangout for active participants: https://plus.google.com/hangouts/_/hoaevent/AP36tYdG3hBo3jlof7toCBR-J4AD2BG5wpKBTd09eukxvlj35npY3A?hl=en&authuser=0

Youtube link to watch: http://youtu.be/GxIj2OZD6yA

Event page: https://plus.google.com/events/ceovda903dtds868toale9rk260

**Comment by mhdawson** [comment]
@nodejs/benchmarking  Reminder of the meeting at 12 EST today.

**Comment by trevnorris** [comment]
Sorry for not being there. For some reason no invite showed up on my calendar.

**Comment by mhdawson** [comment]
Minutes from meeting.  Let me know if anything needs to be modified/updated https://github.com/nodejs/benchmarking/blob/master/meetings/2016-01-07/minutes.md
