### ISSUE TITLE
Submissions to NodeSummit, JS Interactive, NodeConfEU

### ISSUE THREAD

**Issue by mhdawson** [nodejs/benchmarking#211]
Submissions are open to all of these 

NodeSummit submissions are already been evaluated but call is still open
JS Interactive closes April 20
NodeConfEU a bit after that.

Should we be submitting some talks covering the work of this WG for this year?

**Comment by bmeurer** [comment]
I submitted a talk about Promise performance to NodeConfEU, which I guess is related to the benchmarking WG work. But I'm happy to do a joint talk about other benchmarking WG topics at NodeConfEU.

I'm not going to be at either NodeSummit or JS Interactive.

**Comment by mhdawson** [comment]
Discussed in last meeting, don't think we have something interesting enough this cycle.  Will keep thinking but may skip until next  time.
