### ISSUE TITLE
Brainstorm capturing/documenting areas people can contribute

### ISSUE THREAD

**Issue by mhdawson** [nodejs/benchmarking#222]
@detrohutt is volunteering to help document how people can get involved across the project and also to see if we can capture items from working groups and strategic initiatives.

I suggested we start with brainstorming with one or more WGs and this one is first on the list.

**Comment by bmeurer** [comment]
Sounds good. I think the benchmark situation isn't too bad right now, so there aren't that many open issues. One good candidate would be a test suite/benchmark set for measuring/tracking startup performance across different scenarios and using different modules (i.e. also checking the impact of lazy loading). We talked about this with @BridgeAR and @hashseed last week.

**Comment by mhdawson** [comment]
Closing out as we talked about this last meeting.
