### ISSUE TITLE
Membership review

### ISSUE THREAD

**Issue by mhdawson** [nodejs/benchmarking#230]
It may be time to review our membership list.  There are quite a few people that I don't think have been active for quite a while.  

What I'd suggest is:

1) Post an issue with an @ notice to all members asking they confirm they still plan to be active in the WG.
2) Remind after 2 weeks
3) After 4 weeks move all of those who have not responded to 'emeritus'
4) Allow a grace period of 4 more weeks where people can request to be added back without requiring consensus reaching by the WG.

@nodejs/benchmarking  thoughts?

**Comment by gareth-ellis** [comment]
Sounds a good idea

**Comment by uttampawar** [comment]
Yes. I'll be active for sure.

**Comment by jdalton** [comment]
👍

**Comment by mhdawson** [comment]
Opened issue to review membership #235, closing
