### ISSUE TITLE
Membership review - still active?

### ISSUE THREAD

**Issue by mhdawson** [nodejs/benchmarking#235]
Membership review as agreed in: https://github.com/nodejs/benchmarking/issues/230

Michael Dawson (@mhdawson) -> active
Trevor Norris (@trevnorris) -> Emeritus
Ali Sheikh (@ofrobots) -> Emeritus
Yosuke Furukawa (@yosuke-furukawa) -> Emeritus
Yunong Xiao (@yunong) -> Emeritus
Mark Leitch (@m-leitch) -> Emeritus
Surya V Duggirala (@suryadu) -> Emeritus
Uttam Pawar (@uttampawar) -> active
Michael Paulson (@michaelbpaulson) -> active
Gareth Ellis (@gareth-ellis) -> active
Wayne Andrews (@CurryKitten) -> Emeritus
Kyle Farnung (@kfarnung) -> Emeritus
Kunal Pathak (@kunalspathak) -> active
Benedikt Meurer (@bmeurer) -> Emeritus
Sathvik Laxminarayan (@sathvikl) -> Emeritus

Please confirm by posting a comment on this issue if you plan to continue being active in the Benchmark WG. If we don't hear from you we will move you to emeritus as outlined in #230.

**Comment by mhdawson** [comment]
I plan to continue to be active

**Comment by gareth-ellis** [comment]
I plan to remain active

**Comment by kunalspathak** [comment]
+1

**Comment by uttampawar** [comment]
+1

**Comment by mhdawson** [comment]
Ali Sheikh (@ofrobots)
Yosuke Furukawa (@yosuke-furukawa)
Yunong Xiao (@yunong)
Mark Leitch (@m-leitch)
Surya V Duggirala (@suryadu)
Michael Paulson (@michaelbpaulson)
Wayne Andrews (@CurryKitten)
Kyle Farnung (@kfarnung)
Benedikt Meurer (@bmeurer)
Sathvik Laxminarayan (@sathvikl)

This is the second reminder, after 2 weeks we'll remove you from the WG if you don't respond.  There is still a further 4 weeks grace period after that if you simply request to be added back in.

**Comment by mhdawson** [comment]
Trevor Norris (@trevnorris) missed you on last post so doing that here.

**Comment by michaelbpaulson** [comment]
I am in. I have come back from an extended vacation and now moving full time in perf related items. I am sure I'll have time to get back up to speed

**Comment by mhdawson** [comment]
@michaelbpaulson looking forward to seeing you at the next meeting.

**Comment by mhdawson** [comment]
PR landed, review complete
