### ISSUE TITLE
Item for the agenda: Node-land threadpool

### ISSUE THREAD

**Issue by davisjam** [nodejs/benchmarking#239]
Hi @mhdawson and others.

I would like to suggest an agenda item for the next benchmarking WG meeting.
Yesterday's agenda looked pretty sparse so maybe you have space on the next agenda for this?

I would like to discuss the potential implications of [libuv #1726](https://github.com/libuv/libuv/pull/1726), which enables a libuv embedder to define their own threadpool implementation instead of relying on the default libuv threadpool. More on this in [libuv #1959](https://github.com/libuv/libuv/issues/1959).

My question is this: might a Node-land threadpool offer performance improvements in the existing (or potential) benchmark suite?

Ideally we would:
- Discuss what my libuv PR does and what it means for Node.js in general
- Think about which Node.js benchmarks might get a performance boost, and from what Node-land threadpool design(s)
- More broadly, help me get a crash course in the existing benchmark suite and understand any potential benchmarks that are not yet part of the regular suite (so that I can ponder the threadpool implications for them)

**Comment by mhdawson** [comment]
@davisjam were you going to be able to make it to the meeting to discuss this week?

**Comment by davisjam** [comment]
Good conversation, captured in the notes. I'll open additional issues as I find things.
