### ISSUE TITLE
Update charts on benchmarking.nodejs.org for 12.x

### ISSUE THREAD

**Issue by mhdawson** [nodejs/benchmarking#265]
We probably need to update benchmarking.nodejs.org for 12.x

@uttampawar would you like to do it this time around?  We can get together to cover the required steps and I'm pretty sure you already have the access required.

**Comment by uttampawar** [comment]
@mhdawson I've already pushed update to StreamIDs.md file. Do you know other steps we need to take for v12.x? Once this change is done, the remaining step will be to remote v6.x entry.

**Comment by mhdawson** [comment]
I think this past PR shows what needs to be done. IIt swapped in 10.x for 4.x. 
 We need something similar to swap in 12.x for 6.x: https://github.com/nodejs/benchmarking/commit/cdf98c835d15337481e5bb668fd57815a26c22fd

**Comment by mhdawson** [comment]
@uttampawar ^^

**Comment by mhdawson** [comment]
@uttampawar ping?

**Comment by uttampawar** [comment]
@mhdawson Thanks for the reminder. I'll fix it as soon as possible.

**Comment by uttampawar** [comment]
@mhdawson I'll push the changes today.

**Comment by mhdawson** [comment]
Kicked off chart generation after landing @uttampawar's PR. We should see within the next couple of hours or so if the changes look good when they show up on benchmarking.nodejs.org

**Comment by uttampawar** [comment]
@mhdawson Changes look correct for require.perf.js microbenchmark and a new graph line for v12.x instead of v6.x.

**Comment by mhdawson** [comment]
Looks good, closing
