### ISSUE TITLE
Acme air scripts runs longer than expected

### ISSUE THREAD

**Issue by mhdawson** [nodejs/benchmarking#31]
I've set up the scripts and tweaked so we don't get a hang or kill the jenkins agent but it seems to spend a lot of time waiting at this point: 

<PRE>
Perf logs stored in /home/iojs/workspace/benchmark-footprint-experimental-0.12.x/benchmarking/experimental/benchmarks/results///20160225-164357

Cleaning up

## END acmeair Archiving Thu Feb 25 16:49:26 CST 2016
</PRE>

@gareth-ellis  can you take a look ? 

The net is that the jobs take ~11 mins versus the ~6 that we expected. For example: https://ci.nodejs.org/job/benchmark-footprint-experimental/120/

**Comment by gareth-ellis** [comment]
Do you mean after the END acmeair message we wait around for a while before them being killed off?

From the time stamps that are printed, it seems the acme air run (for 120 anyway) was 5mins 29 seconds.

I've checked in a change under 2db045c1d30b7efb15b9027967562b6fdfec5689 that keeps track of child pids (the sleep 600). This isn't a great way of doing it, it'd be good to understand why the getting children and grandchildren of this shell command in kill_bkg_processes isn't working on the benchmark machine. 

That way, we could remove lots of the recording of PIDS throughout the script.

I commented out the line to get child and grandchild pids of the current shell and tested on a machine here, and my change  seems to kill off the timeout now - I don't think I have access to relaunch the test on the community ci to double check there though.

**Comment by gareth-ellis** [comment]
The runs over the weekend seem to be running faster - 6mins 59seconds for https://ci.nodejs.org/job/benchmark-footprint-experimental/125/ vs 11minutes for 120 .

**Comment by mhdawson** [comment]
The 6-7 minutes is closer to what I expected so your change probably made the difference.

**Comment by mhdawson** [comment]
Closing as resoveld
