### ISSUE TITLE
Adding @puzpuzpuz to @nodejs/benchmarking

### ISSUE THREAD

**Issue by Trott** [nodejs/benchmarking#311]
New Collaborator @puzpuzpuz would like to be on the correct team for the benchmarks in Node.js core. It's not clear to me if @nodejs/benchmarking is the right group or not. Is it safe for me to go ahead and add them to @nodejs/benchmarking or does the Benchmarking Workgroup (is it still active?) have a different process?

/cc @addaleax

**Comment by Trott** [comment]
(By the way, @addaleax noticed that @mmarchini is on @nodejs/benchmarking but not listed in the README in this repo.)

**Comment by mmarchini** [comment]
The WG is being de-charteted (https://github.com/nodejs/TSC/issues/822) which is why I didn't add my name to the readme. But the GitHub team will be kept for notifications, so +1 on adding @puzpuzpuz to it.

**Comment by Trott** [comment]
Ah, in that case, yeah, seems like the obvious thing to do is to add them. Done!
