### ISSUE TITLE
Feature Request: Graphs with 0-based Y-axis

### ISSUE THREAD

**Issue by Trott** [nodejs/benchmarking#33]
The graphs at https://benchmarking.nodejs.org/ can be a little misleading if you don't notice that the Y-axis doesn't start at zero. So, for example, the graphs seem to exaggerate the start/stop time differential between 0.12 on the one hand and 4.x and 5.x on the other.

Any chance it's easy enough to make the graph Y-axis start with zero so that these comparisons are more proportional?

**Comment by mhdawson** [comment]
I'm not sure that starting at zero would be better.  In the cases where the numbers are large it would end up hiding differences.  The way its easier to see when one is higher/lower than the others and it does not take that much to figure out what the actual delta is see whether it is significant or not.

**Comment by mhdawson** [comment]
Discuss in latest benchmarking WG meeting.  Consensus for those with an opinon seemed to be for now that it is better to see the variance as opposed to potentially hiding by starting at 0.  Rich unless you object I I'd like to close this one for onw.
