### ISSUE TITLE
Do we have master vs release vs LTS benchmarks?

### ISSUE THREAD

**Issue by mikeal** [nodejs/benchmarking#39]
We have a few scattered reports of perf regressions in V8. It would be good to know about these before we close in on a major release so having an ongoing comparison with master and the release lines would be good.

**Comment by gareth-ellis** [comment]
Hi @mikeal 

At the moment we master, v4.x and v0.12.x on the charts at https://benchmarking.nodejs.org/

Is that the sort of thing you're after, or from another stream? My understanding is that it shouldn't be too much work to include some extra builds if there's different ones required.

**Comment by mikeal** [comment]
this is great! :)
