### ISSUE TITLE
Run benchmarks on 6.x and add to charts

### ISSUE THREAD

**Issue by mhdawson** [nodejs/benchmarking#40]
We need to:

- [x] add stream id to https://github.com/nodejs/benchmarking/blob/master/benchmarks/StreamIDs.md
- [x] add job to run benchmarks on 6.X
- [x] add entry in json config for each benchmark to add display of 6.x data on charts
- [x] validate charts show data and all looks ok
- [x] Updated job to point at 6.X stream when its cut

**Comment by mhdawson** [comment]
Added new job with stream id for 6.x. https://ci.nodejs.org/job/benchmark-footprint-6.x/.  For now it just runs on master as well but that's equivalent to what 6.x will be.  When 6.x is cut we'll make it point at that branch.

**Comment by mhdawson** [comment]
Have added the following to the config files in my repo:
 {"streamid": 4, "name": "6.x", "color": "DarkMagenta" }

will commit once we have a at least one day of data captured against the 6.x stream

**Comment by mhdawson** [comment]
committed addition to configuration files to add display of 6.X, will check graphs on Monday

**Comment by eljefedelrodeodeljefe** [comment]
@mhdawson the charts being shared by some guys currently come from this, right? As an external to the group, could you shed some light on the tooling?

**Comment by mhdawson** [comment]
This page describes the infrastructure flow:  https://github.com/nodejs/benchmarking/blob/master/benchmarks/README.md.  If you have other questions just let me know.

**Comment by mhdawson** [comment]
Switched over to 6.x branch, closing
