### ISSUE TITLE
Benchmarking use cases

### ISSUE THREAD

**Issue by mhdawson** [nodejs/benchmarking#5]
This issue is for us to discuss what use cases we need Node benchmark to cover.

Two initial ones are 
+ front end gui
+  back end services

but we'd like to get more specific and make sure we have one for each of the important ways that Node is used.

**Comment by mhdawson** [comment]
Two use cases from earlier discussion here: https://nodejs.org/about/core-team/meetings/2015-03-26/minutes.html

 + low-latency
 + high concurrency.

**Comment by yunong** [comment]
Our current Node deployment at Netflix consists almost entirely of front end GUI services. We use ReactJS to render the markup server side. We use Restify as the HTTP framework for these apps.

Predominantly, where we're seeing performance bottlenecks comes predominantly from rendering the mark up in ReactJS. We're seeing 2-400 ms on CPU in React when we're rendering a page.

It'd be good to integrate both React and Restify into the benchmarks, to give us an idea of where each framework stands in terms of performance.

**Comment by yunong** [comment]
As part of our discussion from the last meeting, HTTP/2 and Websockets are used today for full duplex communication between client and services in Node.js. In particular, there's been a shift for both back end and front end apps to move towards the bi-directional communication model. In particular, the ability for servers to 'push' events to the client.

Both of these currently are 3rd party modules https://einaros.github.io/ws/ and https://github.com/molnarg/node-http2

**Comment by mhdawson** [comment]
Closing as we have captured in 18eaa6d00d37fb3ac664db2873817e0c7c901083
