### ISSUE TITLE
Indicate whether higher or lower numbers are better for each chart

### ISSUE THREAD

**Issue by rayshan** [nodejs/benchmarking#50]
Hi! It's not clear at a glance whether higher or lower numbers are better for each chart. For example, for the Start + Stop Time chart, viewer has to understand y-axis is time, thus lower numbers are better for that chart.

**Comment by gareth-ellis** [comment]
I'll have a word with @mhdawson later, it should be an easy enough change to add it.

Perhaps to the y axis - have what is measured plus higher or lower is better.

i.e. Throughput - higher is better 

Does that sound suitable?

**Comment by mhdawson** [comment]
Adding a label somewhere should be pretty easy.  I'll look at doing that next week

**Comment by rayshan** [comment]
Sure, thanks guys. I think it's typically done as a footnote at the bottom of the chart to not take up too much space next to the y axis.

**Comment by mhdawson** [comment]
Initial change to add the data https://github.com/nodejs/benchmarking/pull/51/files

Will update later on to make it prettier by adding a single line somewhere in the chart and having it configurable through a separate element in the json.

**Comment by mhdawson** [comment]
Even though PR is not landed, pushed change to benchmark machine generating graphs. You can see the new text at https://benchmarking.nodejs.org/

**Comment by mhdawson** [comment]
PR landed, closing.  Will look to do better next time we refactor the generation.
