### ISSUE TITLE
nightly benchmark jobs failing on master

### ISSUE THREAD

**Issue by mhdawson** [nodejs/benchmarking#53]
Seem to have been failing since last week:

https://ci.nodejs.org/view/Node.js%20benchmark/job/benchmark-footprint-experimental/283/console

/home/iojs/build/workspace/benchmark-footprint-experimental/node/bin:/home/iojs/build/workspace/benchmark-footprint-experimental/node/out/Release/:/usr/lib/ccache:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
+ cd ..
+ mkdir bench
+ cd bench
+ node /home/iojs/build/workspace/benchmark-footprint-experimental/node/benchmark/report-startup-memory.js
module.js:442
    throw err;
    ^

Error: Cannot find module '/home/iojs/build/workspace/benchmark-footprint-experimental/node/benchmark/report-startup-memory.js'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:340:7)
    at startup (bootstrap_node.js:132:9)
    at bootstrap_node.js:455:3
+ RESULT=
Build step 'Execute shell' marked build as failure

**Comment by mhdawson** [comment]
Seems required file was removed as part of this:

**Comment by gareth-ellis** [comment]
https://github.com/nodejs/node/commit/ee2843b4ea54b04eca30e00ec1ab39206449bd52

Perhaps we can just pull that one into our repo? Seems only a few lines

**Comment by mhdawson** [comment]
Yes doing that now.
