### ISSUE TITLE
Next Benchmarking meeting - Nov 2016

### ISSUE THREAD

**Issue by mhdawson** [nodejs/benchmarking#69]
# Who

@nodejs/benchmarking 
# When

Set for Friday Nov 18 at 4PM EST.

TBD Based on doodle poll: http://doodle.com/poll/pqiiexb6fnrtb769 (CLOSED)
# Where

link for participants: https://hangouts.google.com/hangouts/_/ytl/U28I1m3rIBX7vUZequdQb2ENxYTDuDO-InqdTSRmYR0=

For those who just want to watch: http://youtu.be/DNBx4YGFa2g
Google doc for minutes :https://docs.google.com/document/d/1PwmuSKGA5Hbnd_8NVbu2pRm3fz4gZYaWD29jzQZ7rlE/edit

# Agenda
- Stand up 
- Actions from last meeting
- membership https://github.com/nodejs/benchmarking/issues/70
- https://github.com/nodejs/benchmarking/pull/63
- Open issues/PR review

# Actions from last meeting

**Comment by mhdawson** [comment]
@nodejs/benchmarking please fill in doodle poll with your availablity.

**Comment by mhdawson** [comment]
@nodejs/benchmarking meeting time set based on doodle poll.
@currykitten FYI as well.

**Comment by gareth-ellis** [comment]
@mhdawson  the participant link seems to be giving a 403 not authorised....

**Comment by mhdawson** [comment]
Not sure why'd you see that I just used the link to join.  Maybe it should just be:

https://hangouts.google.com/call/wuiaos42jzh6lbfq3mkaklx3uae

**Comment by mhdawson** [comment]
Sorry for the delay having trouble getting it to let me start recording.

New link: https://hangouts.google.com/hangouts/_/ytl/U28I1m3rIBX7vUZequdQb2ENxYTDuDO-InqdTSRmYR0=

**Comment by mhdawson** [comment]
PR for meeting minutes: https://github.com/nodejs/benchmarking/pull/78

**Comment by mhdawson** [comment]
Minutes landed so closin.
