### ISSUE TITLE
Benchmarking WG members - still interested ?

### ISSUE THREAD

**Issue by mhdawson** [nodejs/benchmarking#70]
I've seen some of the WG's re-confirming membership by polling the WG members to make sure people are still interested/willing to be active.

Its probably time to do that for the benchmarking WG meeting.

Please respond to this issue confirming you are still interested and are willing to be active.  Based on this information we'll trim down the WG membership to those who will be participating going forward.

@nodejs/benchmarking

**Comment by mhdawson** [comment]
I still plan to be active :)

**Comment by ofrobots** [comment]
I haven't been active lately, but plan to be active.

**Comment by michaelbpaulson** [comment]
I am still active

**Comment by gareth-ellis** [comment]
I intend to remain active too

**Comment by mhdawson** [comment]
@nodejs/benchmarking second call.  The people who have responded are those who have been active recently.  

We will discuss at the meeting this Friday if we should trim the membership list based on who has responded.  If you still want to be involved or on the @nodejs/benchmarking list please chime in.

**Comment by uttampawar** [comment]
@mhdawson: I intend to be active (uttam.c.pawar@intel.com) going forward. Please add me to the list.

**Comment by emanuelbuholzer** [comment]
@mhdawson I'd like to join/be active in this working group. I don't know if this is the correct place to state this but you could contact me at contact@emanuelbuholzer.com for a short discussion about this. :)

**Comment by gareth-ellis** [comment]
@emanuelbuholzer , as an fyi, there's an issue open at the moment for planning the next meeting - #84 , fill in your availability on the doodle

**Comment by kunalspathak** [comment]
@mhdawson - It was pleasure talking to you in the meeting on Jan 12th. I would like to join the working group.

**Comment by mhdawson** [comment]
Going to close this for now.
