### ISSUE TITLE
Vanilla anyone?

### ISSUE THREAD

**Issue by a0viedo** [nodejs/benchmarking#71]
Hallo!

I found some [loop constructs](https://github.com/nodejs/node/blob/master/lib/events.js#L477) in the source that I think are intended for better performance but couldn't find any context for them.
I'm trying to go around some benchmarks for vanilla JavaScript and I couldn't found any on the WG or anywhere else. So bear with me and please let me know if there are holes in the logic here.
  
## Array cloning
Executed the [sample snippet](https://gist.github.com/a0viedo/b10d4adc385b8c3b69acce79430fbce6) 200 times to plot. Watching the output for `--print_opt_code`, both functions measured are being picked up by Crankshaft and as far I can see they're not running into DCE.

### Node v4
![](http://imgur.com/0vOdWk8.png)

### Node v6
![](http://imgur.com/I8dzzDf.png)

### Node v7
From the graph it appears now that the for-loops are targeted with the same optimizations (why on other versions of V8 they wouldn't?!).
![](http://imgur.com/O0D1r98.png)

## Array sum
The snippet that I'm running is [this one](https://gist.github.com/a0viedo/4d1f1eb307913f7f68bfaca631ec00ae). It might not change from one algorithm to another but the improvements from Node v6 are remarkable. From all three plots seems like the decreasing for-loop gets more stable in the latest versions of V8.

### Node v4
![](http://imgur.com/9l40Ndc.png)

### Node v6
![](http://imgur.com/PlPrwDm.png)

### Node v7
![](http://imgur.com/8SnTMHn.png)

I don't care about changing existing code but I think it would be useful to understand which would be the process for choosing one implementation over another.

Pending questions would be:
- Will the results be consistent across platforms?
- Does V8 have some tests similar to this?

**Comment by fhinkel** [comment]
I thought [this](https://chromium.googlesource.com/v8/v8/+/6e665b094e7cbb6187fb59e3eb135266fa4c2e96) makes the decreasing loop as fast as increasing ones, but it came in with v7, not v6 🤔.  So it doesn't quite fit your results. 

We currently look at [these benchmarks](https://fhinkel.github.io/six-speed/). They compare "vanilla" ES5 implementations with similar ES6 implementations. 

Maybe I'm missing it, but how does the decreasing while loop compare to `Array.prototype.slice()` in Node7? The change was made 18 month ago, optimizations are probably different now. Maybe we can replace the custom copy method with a simple `slice`. 

Can you run the benchmarks mentioned in the [commit message](https://github.com/nodejs/node/commit/555a7c48cf3b038f9627591cf51b68387f8de36a) and see if they still need `while(i--)`?

**Comment by mhdawson** [comment]
My understanding is that v8 uses octane as a Javascript benchmark: https://developers.google.com/octane/ not sure if it has a test specifically for the case you are covering though.   It think its more real-world application oriented so quite likely not.

**Comment by mhdawson** [comment]
@ofrobots are you aware of any other micro-benchmarks used by the V8 team ?

**Comment by fhinkel** [comment]
We have some micro-benchmarks here: https://github.com/v8/v8/tree/master/test/js-perf-test

**Comment by a0viedo** [comment]
Included `Array.prototype.slice` as @fhinkel suggests:

## v4
![](http://imgur.com/TWUUw52.png)

## v6
![](http://imgur.com/3QUqB69.png)

## v7
![](http://imgur.com/DbEHh0k.png)

Would love to graph node-chakra's results once they enable JIT.

**Comment by fhinkel** [comment]
Double checking: So slice is faster than the other options? And always was faster?

You can compare to node-chakra on Windows (jitted there).

**Comment by mhdawson** [comment]
Any more discussion here or has it run its course ?

**Comment by mhdawson** [comment]
Its been 3 months since there has been any discussion. Going to close please re-open if more discussion is needed.
