### ISSUE TITLE
Add @jbajwa to v8 team

### ISSUE THREAD

**Issue by mhdawson** [nodejs/benchmarking#76]
Note sure were else to post this so here it goes.

Would like to add 
@jbajwa to the team https://github.com/orgs/nodejs/teams/v8.  He works on keeping the Power and s390 ports up to date and it would be good for him to be copied on issues that go out to the v8 team.

@nodejs/v8 any objections ?

**Comment by ofrobots** [comment]
+1

**Comment by bnoordhuis** [comment]
No objections.

**Comment by targos** [comment]
No objection

**Comment by jbajwa** [comment]
Thank you, I've joined the nodejs/v8 team.
