### ISSUE TITLE
Benchmarking meeting Thursday Jan 12 2017

### ISSUE THREAD

**Issue by mhdawson** [nodejs/benchmarking#84]
Who

@nodejs/benchmarking 

# When

From doodle (http://doodle.com/poll/gpfsa3tf3buxfq5w) 2pm est Thursday Jan 12 2017

# Where

link for participants: https://hangouts.google.com/hangouts/_/ytl/zeaYO6qoqWnSmMgfrlxg3cEhqrN6xseejwzELEfH-zQ=?eid=100598160817214911030&hl=en_US&authuser=0

For those who just want to watch: http://youtu.be/E9ToYdEkRHc

youtube admin page: https://www.youtube.com/my_live_events?filter=scheduled

Google doc for minutes: https://docs.google.com/document/d/1EG9JA2bhgVT6v4LHf1KVCiky-t3q-60rYNVvc17hwyk/edit

# Agenda
- Stand up 
- Actions from last meeting
- Review https://github.com/nodejs/benchmarking/pull/55 and talk about how to fill in gaps
- Review https://github.com/nodejs/benchmarking/issues/86
- Review https://github.com/nodejs/benchmarking/issues/63
- Open issues review

# Actions from last meeting

* Michael and Gareth to work on additional benchmarks as discussed above
* all - review https://github.com/nodejs/benchmarking/pull/63 so we can discuss again in the next meeting

**Comment by mhdawson** [comment]
Based on doodle will set for 2PM on Thursday Jan 12.

**Comment by mhdawson** [comment]
@nodejs/benchmarking @sathvikl time has been set.

**Comment by williamkapke** [comment]
19:00 UTC

https://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js+Benchmarking+WG+Meeting+2017-01-11&iso=20170111T19

**Comment by gareth-ellis** [comment]
Is the meeting starting soon?

**Comment by williamkapke** [comment]
This meeting happened- however there was an error with getting it to stream live. :(

**Comment by mhdawson** [comment]
PR for meeting minutes https://github.com/nodejs/benchmarking/pull/89

**Comment by mhdawson** [comment]
Minutes landed, closing
