### ISSUE TITLE
show current value on graphs for each branch

### ISSUE THREAD

**Issue by mscdex** [nodejs/benchmarking#87]
Since in many places there is a lot of visual overlap between branches in the benchmark graphs, it would be help to have some way to easily see where the current branch is on the graph. For example, right now it's hard to see where the master branch exactly is because it's usually covered up by the v7.x or other branch.

I was thinking about maybe have color-coded, labeled lines on the right-hand side of the graph or something? Or at the very least just have an adjacent box with color-coded current values?

**Comment by mhdawson** [comment]
The easiest might just to have the latest number as part of the existing legend.  Does that make sense to you ?

**Comment by mscdex** [comment]
That's fine, as long as the numbers are easily readable and comparable (e.g. digits aligned and thousands separators).

**Comment by CurryKitten** [comment]
I was looking at the charting generation recently, so I'm happy to pick this up
