### ISSUE TITLE
Special Meeting - Deep Dive on Node-DC-EIS Benchmark suite

### ISSUE THREAD

**Issue by mhdawson** [nodejs/benchmarking#90]
# Who

@nodejs/benchmarking 

# When

Set for Friday Feb 3 9AM EST. 

doodle: http://doodle.com/poll/cav55sf7r5cfxks6 (close)

Poll will close Jan 23.

# Where

link for participants: https://hangouts.google.com/hangouts/_/ytl/9hR8qzRL8Xn0ziosKBY6JMHUG-n0qalXYJLNAajjs2I=?eid=100598160817214911030&hl=en_US

For those who just want to watch: https://www.youtube.com/watch?v=ktGMg8dj6Kk

youtube admin page: https://www.youtube.com/my_live_events?filter=scheduled

# Agenda

Deep dive presentation from Anil/satvik on Node-DC-EIS
https://github.com/Node-DC/Node-DC-EIS

**Comment by mhdawson** [comment]
@williamkapke can you mention this one in the next CTC meeting (I won't be there) and add to the list of upcoming meetings as it would be good to get broader freedback on the benchmark.

**Comment by mhdawson** [comment]
@nodejs/benchmarking need more people to fill in doodle.

**Comment by mhdawson** [comment]
@satvik can you fill in your availability for this one (I see you filled it in for the other one but not this one)

**Comment by sberi-euclid** [comment]
@mhdawson I think you have the wrong Satvik :)

**Comment by Satvik** [comment]
@mhdawson I think you tagged the wrong Satvik, I'm not related to this project :)

**Comment by sathvikl** [comment]
@mhdawson  Thank you. I received the notification. 
Any day except 1/26 and 1/27 will work for us. @AnilKumarRajput

**Comment by mhdawson** [comment]
@williamkapke can you add to general node calendar

**Comment by williamkapke** [comment]
Added! 14:00 GMT on 2017-02-03

**Comment by mhdawson** [comment]
The meeting is live, just giving people a few more minutes to join.  Will start broadcast in 2-3 minutes.

**Comment by mhdawson** [comment]
Presenter is just having some problems joining, we hope to start soon.

**Comment by mhdawson** [comment]
Anil is still having issues, will start once we can get him in.

**Comment by mhdawson** [comment]
Ok, we went live and meeting is now complete.  If you missed it, you should be able to watch the youtube recording.
