### ISSUE TITLE
Move benchmarking.nodejs.org to use SVGs versus PNGs

### ISSUE THREAD

**Issue by mhdawson** [nodejs/benchmarking#93]
From https://github.com/nodejs/nodejs.org/issues/1110#issuecomment-275234548

@silverwind mentioned:

While the logos sizes are now fixed, they PNGs should really be replaced with the SVG versions I added recently. They are 1/8th of the size at no quality loss.

**Comment by silverwind** [comment]
It's a simple URL change. Replace

```
https://nodejs.org/static/images/logos/nodejs-new-white-pantone.png
```
With
```
https://nodejs.org/static/images/logo.svg
```
For light backgrounds, there's also
```
https://nodejs.org/static/images/logo-light.svg
```

**Comment by mhdawson** [comment]
PR https://github.com/nodejs/benchmarking/pull/96
